# Generated by Django 4.2.9 on 2024-02-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github_url',
            field=models.URLField(blank=True),
        ),
    ]
